- man/feh.pre
- src/winwidget.c
This allows setting a *maximum window size* when viewing images.
> Make --scale-down work with --geometry.

- man/feh.pre
Add description of option "--no-recursive" to man page.
> Add "--no-recursive" to man page

- src/feh_png.c
> src/feh_png.c: close file upon error

- src/winwidget.c
FreeBSD lacks the constant HOST_NAME_MAX, instead using sysconf(3) to
find out the value of the maximum host name length at run time.  Patch
to use this instead of HOST_NAME_MAX.
This brings with it the need to use malloc instead of using a statically
sized buffer for the host name, since the size of the buffer cannot be
known at run time.  Errors from sysconf or malloc just means that the
entire block of code is skipped over (the same way it's skipped if the
call to gethostname() fails), rather than returning any kind of error to
the caller or logging an error message somewhere.
> Fix build on FreeBSD.

- config.mk
- src/help.raw
- src/imlib.c
- src/options.c
- src/options.h
there is probably a very good reason the autorotate code has been half-finished for 3 years (for one, it adds 0.15s on average on my machine), so i know this PR probably wont actually be merged.
im making this PR just so that someone who sees it in the issues can quickly build it for themselves.
(the previous code always got orientation=0 for MOTOROLA byte order)
#86
> exif autorotate cmdline opt

- src/imlib.c
* Prevents nasty loading loops
* Prevents zombie subprocesses
* Fixes the conversion timeout detection routine
The `convert` exit status is unreliable. Warnings seem to be treated as errors.
`WIFSIGNALED(status)` has always returned `NULL`.
`alarm(opt.magick_timeout)` does not kill any subprocesses (ffmpeg, ...) created by `convert`.
> Fix the --magick-timeout handling

- src/slideshow.c
Fixes issue #325. Not sure if this is the best way since it rereads the file though?
> Add files from file list file on reload.

- src/winwidget.c
> Improve screen clip feature

- src/help.raw
- src/options.c
- src/options.h
- src/slideshow.c
> Add --no-cycle option

- src/slideshow.c
Reference: https://github.com/derf/feh/pull/366#issuecomment-417040289
> This will fix 'jump_last' and 'jump_first' when using no-cycle

- src/winwidget.c
It is a naive way of fixing it :) Needs attentive review
Check https://github.com/derf/feh/issues/440 for more details
> Remove useless assignments

- share/applications/feh.pre
Add ```.webp``` filename extension (```image/webp``` internet media type)
> Add WebP image format

- src/imlib.c
Fixes https://github.com/derf/feh/issues/580
> Fix truncated image file descriptor leak

- src/feh_png.c
- src/filelist.c
- src/imlib.c
- src/slideshow.c
- src/wallpaper.c
Different attempt at fixing warnings from `gcc`. All of them on my system, who knows about other compilers.
> Fix some warnings from `gcc`.

- src/utils.c
Both of these protocols are supported in latest curl.
> Add support for gopher and gophers in utils/path_is_url.

- src/imlib.c
The exif code path triggers out of boundary access. It is a bit hard to see, so I have added a formatting commit. Feel free to skip that one or squash both commits into one.
> Fix out of boundary access with exif

- share/applications/feh.pre
As of 1.8, imlib2 supports heic
https://phab.enlightenment.org/T8877
> add heic support

- man/feh.pre
- src/help.raw
Documentation update per issue #714
> document new name of `--cycle-once`

- src/menu.c
This is a right-click crash issue fix.
https://github.com/derf/feh/issues/676
> Fix for right-click buffer overflow

- src/options.c
> Fix --no-recursive bug

- share/images/feh.svg
Remove unused svg markup from file "share/images/feh.svg" to reduce its size.
> Reduce size of "share/images/feh.svg"
