derf/feh

man/feh.pre, src/options.c, src/options.h, src/wallpaper.c
The following code is used to render a background image for a single X head. Had a system where two heads were being overlapped on multiple displays. I wanted to be able to have `feh` set the background for either A or B (depending on the user's preference).
```
|---------------------|
|      A     |        |
|------------|    B   |
|                     |
|---------------------|
```
From this, a user could configure (for example) on area A by invoking the following:
> feh image.png --bg-scale --xinerama-index 0
=> Support Background Setter for a Single Display

src/slideshow.c
I think it's better than skipping back to the first image
=> slideshow: When removing last image, stay on the last image

src/events.c, src/events.h, src/keyevents.c, src/winwidget.c
This should help clean the --scale-down "mess" #81 by ensuring that `feh` after mapping its window correctly knows its current window size.
I have only tested this in `ratpoison` where the `ConfigureNotify` event seems to always precede the `MapNotify`, resulting in incorrect rendering of the first image of any slideshow. Behaviour on other WM's is not tested, feel free to comment if this change does not work for yours!
I have some more things coming to avoid the double-rendering / flicker as discussed in #54, but I'm not completely happy with those changes.
=> events: also react to ConfigureNotify after mapping

man/feh.pre, src/help.raw, src/imlib.c, src/options.c, src/options.h
Changes:
* Added an `--insecure` option to disable host/peer verification in libcurl.
This allows `feh` to load images on HTTPS hosts with self-signed certificates.
For security, this is not the default.
* Fixed an include in `show_usage`.
* Removed some trailing whitespace.
=> Allow HTTPS connections with self-signed certs, plus an include fix/trailing whitespace removal

src/options.c
Purpose of "--no-recursive" option is disabling effect of "--recursive" option that enabled by user's theme.
=> Add option "--no-recursive"

src/wallpaper.c
The if statements are needed because we cannot pass a NULL pointer to
XFree.
=> src/wallpaper.c: free up some data allocated by X.

src/main.c
These two sections get malloc'ed when reading the options but never free'd. I put them in the cleanup method to make sure they aren't free'd before needed.
=> src/main.c: free the malloc'ed sections of the options

src/main.c
XCloseDisplay never gets called for `disp` so it is still around when the program is exiting.
=> src/main.c: Clean up the Display variable upon exiting

src/main.c
One of my previous changes introduced the fix below but I used spaces and not tabs to do this. The new version of GCC complains about misleading indentation so I feel compelled to fix this warning.
=> src/main.c: switch spaces to tabs to clobber GCC warning

Makefile, man/feh.pre, src/keyevents.c, src/options.h
Ads a non-sticky zoom to fill to key bindings.  (Allowing a user to see how a background switcher or slide show would effect the current image.)
Updated the man pages.
Fixed a minor 'build break' for the README. (Not sure this is 100% the 'correct' way.)
=> Added a "zoom fill" key binding for the current image.

src/wallpaper.c
If a malicious client pretends to be the E17 window manager, it is
possible to trigger an out of boundary heap write while receiving an
IPC message.
The length of the already received message is stored in an unsigned
short, which overflows after receiving 64 KB of data. It's comparably
small amount of data and therefore achievable for an attacker.
When len overflows, realloc() will either be called with a small value
and therefore chars will be appended out of bounds, or len + 1 will be
exactly 0, in which case realloc() behaves like free(). This could be
abused for a later double-free attack as it's even possible to overwrite
the free information -- but this depends on the malloc implementation.
=> Fix double-free/OOB-write while receiving IPC data

src/utils.c
If ereadfile encounters an empty file or the file could not be read, an
out ouf boundary read (and possible write) occurs. Always check the
return value of fread to be > 0 before processing the result buffer.
=> Avoid out of boundary read on empty/broken file.

src/collage.c, src/index.c, src/thumbnail.c
The strncpy function does not guarantee to end the resulting character
sequence with a terminating nul character if not enough space is
available. This could be triggered by supplying a sufficiently long
output_file option.
=> Always terminate strncpy results with '\0'.

src/utils.c
If feh_unique_filename encounters a file that already exists, the memory
for the temporary filename is not released. As this happens in /tmp at
some code places, an attacker could use this to spray the memory of feh,
or simply triggering an out of memory condition.
=> Fixed memory leak on file name collision.

src/utils.c
If malloc cannot allocate enough memory, it could return NULL. This is
not necessarily true for default Linux settings, but can be provoked
there as well by adjusting proc entries. Other systems like the *BSD
ones definitely do this.
The function _emalloc exists for exactly this purpose, so use it instead
of calling malloc directly.
=> Check malloc return value for NULL.

src/feh_png.c, src/feh_png.h, src/thumbnail.c
This implements changes to the thumbnail generation to use `$XDG_CACHE_HOME`, respectively `$HOME/.cache/thumbnails`, c.f. #283. It's in "works for me" state, I was unsure about the different styles in the existing code and how much additional error checking should be done here.
=> Use XDG folders for thumbnails.

src/imlib.c, src/utils.c
Silences the following two warnings with gcc-7.2.0. Please review to make sure this solution is correct.
```
imlib.c: In function ‘feh_draw_actions’:
imlib.c:1327:19: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
sprintf(index, "%d", i);
^~~~
imlib.c:1327:4: note: ‘sprintf’ output between 2 and 3 bytes into a destination of size 2
sprintf(index, "%d", i);
^~~~~~~~~~~~~~~~~~~~~~~
utils.c:170:34: warning: ‘%06ld’ directive output may be truncated writing between 6 and 11 bytes into a region of size 10 [-Wformat-truncation=]
snprintf(cppid, sizeof(cppid), "%06ld", (long) ppid);
^~~~~
utils.c:170:33: note: directive argument in the range [-2147483648, 2147483647]
snprintf(cppid, sizeof(cppid), "%06ld", (long) ppid);
^~~~~~~
utils.c:170:2: …
```
=> Silence warnings

src/Makefile
The current `src/Makefile` globs the all of the `*.c` files in `TARGETS` and will compile them even if their contents are hidden behind an `#ifdef` and essentially empty which will result in the following warnings.
```
cc -g -O2 -Wall -Wextra -pedantic -DHAVE_LIBCURL -DHAVE_LIBXINERAMA -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"2.19.3-4-g5cf2736\"   -c -o exif.o exif.c
exif.c:318:0: warning: ISO C forbids an empty translation unit [-Wpedantic]
#endif
cc -g -O2 -Wall -Wextra -pedantic -DHAVE_LIBCURL -DHAVE_LIBXINERAMA -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"2.19.3-4-g5cf2736\"   -c -o exif_canon.o exif_canon.c
exif_canon.c:61:0: warning: ISO C forbids an empty translation unit [-Wpedantic]
#endif
cc -g -O2 -Wall -Wextra -pedantic -DHAVE_LIBCURL -DHAVE_LIBXINERAMA …
```
=> (src/Makefile) Manually set the target *.c files

src/options.c
Silences the following warning, my understanding is that `break;` was just accidentally left out here.
```
options.c: In function ‘feh_parse_option_array’:
options.c:770:21: warning: this statement may fall through [-Wimplicit-fallthrough=]
opt.insecure_ssl = 1;
~~~~~~~~~~~~~~~~~^~~
options.c:771:3: note: here
case 241:
^~~~
```
=> Silence -Wimplicit-fallthrough= warning

src/imlib.c
The patch silences two warnings. First I remove an unused variable, secondly, I fix an if conditional that previously was always false, to do what is intended. I then have to fix the dead code now available. I hope the commit messages are clear for these changes, otherwise let me know if I need to explain more.
Thanks!
=> silence comple warnings and fix previous dead code

src/imlib.c
Hello!
This patch makes `feh` respect `$CURL_CA_BUNDLE`, just like `curl` does.  This makes it possible for users to specify a custom certificate directory instead of the `libcurl` builtin.
=> imlib: Look up CA certificates by $CURL_CA_BUNDLE.

src/winwidget.c
This prevents removing the image data from the cache, when moving back and forth between images. As suggested by the Imlib documentation: http://alien.cern.ch/cache/imlib2-1.0.6/doc/
This significantly reduces the delay in toggling between two images, when both images are in the imlib cache.
=> Utilize the imlib cache properly

src/help.raw, src/imlib.c, src/options.c, src/options.h
This option allows you to change the imlib2 image cache size.
Maybe we should also consider increasing the default cache size, which seems to be 4 MiB.
=> Add option to change the imlib cache size

src/winwidget.c
This will prevent unnecessary calls to `feh_calc_needed_zoom`.
=> Only calculate required zoom ratio when necessary

src/list.c, test/nx_action/loadable_action, test/nx_action/loadable_naction, test/nx_action/unloadable_action, test/nx_action/unloadable_naction
On glibc, if output is redirected to a file, output will look like this:
touch test/ok/gif
touch test/ok/jpg
touch test/ok/png
touch test/ok/pnm
test/ok/gif
test/ok/jpg
test/ok/png
test/ok/pnm
On musl, if stdout is redirected to a file, output looks like this:
test/ok/gif
touch test/ok/gif
touch test/ok/jpg
touch test/ok/png
touch test/ok/pnm
test/ok/jpg
test/ok/png
test/ok/pnm
On glibc and musl, if stdout is interactive, it looks like this:
test/ok/gif
touch test/ok/gif
test/ok/jpg
touch test/ok/jpg
test/ok/png
touch test/ok/png
test/ok/pnm
touch test/ok/pnm
Adding two fflush calls makes all behavior look like the last example.
Test cases have been updated accordingly.
=> fflush in src/list.c to make tested behavior consistent across glibc and musl

config.mk
With `-D_XOPEN_SOURCE=500`, there appears to be some sort of namespace conflict between strings.h and feh's source, specifically with regards to `index` or `rindex`. This prevents compilation on musl:
```
cc -g -O2 -Wall -Wextra -pedantic -std=c11 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=500 -DHAVE_LIBCURL -DHAVE_LIBXINERAMA -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"2.23\"   -c -o options.o options.c
In file included from feh.h:33:0,
from options.c:27:
/usr/include/strings.h:19:7: error: expected declaration specifiers or '...' before '(' token
char *index (const char *, int);
^
/usr/include/strings.h:19:7: error: expected declaration specifiers or '...' before '(' token
char *index (const char *, int);
^
/usr/include/strings.h:20:7: error: expected declaration specifiers or …
```
=> Adjust CFLAGS to fix compilation on musl

src/slideshow.c
Halves the slideshow start-up time if the title contains data from `file->info`.
The title is regenerated later anyway: https://github.com/derf/feh/blob/master/src/winwidget.c#L637-L639
Speed comparisons of the time it takes to finish rendering the first image of the slideshow:
| `--title <...>`  | Before | After |
| ------------- | ------------- | ------------- |
| `"[%u/%l] %n"`  |  0.220 s  |  0.220 s  |
| `"[%u/%l] %n (%wx%h)"`  | 0.397 s |  0.224 s  |
Sample images taken from this gallery: https://www.dpreview.com/sample-galleries/9485291827/canon-eos-5d-mark-iv-sample-gallery/5126624650
=> Remove unnecessary code

src/filelist.c, src/slideshow.c
This will (by default) check the image dimension on-the-fly, but you can still do it beforehand by specifying the preload flag.
Fixes: #164
=> Handle --min-dimension and --max-dimension without preload

src/feh.h, src/filelist.c, src/help.raw, src/options.c, src/options.h
Adds a new option `--version-sort` similar to `ls -v`.
Closes: https://github.com/derf/feh/issues/344
@derf, please let me know if you dislike the current solution, which is built around `strverscmp` which requires `#define _GNU_SOURCE`.
=> Add natural sort of (version) numbers

src/keyevents.c
This will update the window dimensions and rerender the current image when the `toggle_fixed_geometry` event is raised.
Without this you have to jump back and forth between two images to get the desired effect.
=> Apply the toggle_fixed_geometry event to current image

man/feh.pre
This fixes many warnings shown by mandoc lint feature and should also respect
the 80 col limit.
```
man -Tlint feh
```
```
WARNING: new sentence, new line
```
```
new sentence, new line
(mdoc) A new sentence starts in the middle of a text line. Start it on a new
input line to help formatters produce correct spacing.
```
```
man: /usr/man/man1/feh.1.gz:35:32: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:78:33: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:90:50: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:95:53: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:97:23: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:108:17: WARNING: new sentence, new line
man: /usr/man/man1/feh.1.gz:112:36: WARNING: new sentence, new line …
```
=> feh.1: Fix mandoc warnings

man/feh.pre
This fixes the following mandoc warnings.
```
man -Tlint feh
```
```
WARNING: skipping empty macro: No
```
```
skipping empty macro
(mdoc) The indicated macro has no arguments and hence no effect.
```
https://man.openbsd.org/mandoc.1
```
man: /tmp/man1/feh.1:16:14: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:16:34: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:179:2: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:387:48: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:785:26: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:785:38: WARNING: skipping empty macro: No
man: /tmp/man1/feh.1:823:26: WARNING: skipping empty macro: No
```
As the warning suggests, these seem to have no effect and are just ignored. I at least did not notice any difference …
=> feh.1: Silence mandoc warnings

src/wallpaper.c
Hi,
I noticed that the option `--bg-max` ended up `--bg-fill` in the `.fehbg` file.
This PR fixes the issue.
Best regards
rand-0m
=> bugfix: .fehbg output for --bg-max

src/options.c, src/options.h, src/slideshow.c, src/winwidget.c, src/winwidget.h
This simplifies the logic behind the automatic zoom ratio calculation, which is used by both `--auto-zoom` and `--scale-down`.
When merged this will:
* Improve the performance (especially in fullscreen mode)
* Fix the `w` command when both `--scale-down` and `--keep-zoom-vp` are enabled
* Fix `--auto-zoom` not being triggered on window resize events when `--scale-down` is enabled
* Fix `--auto-zoom` not being applied to the first image
* Fix `--auto-zoom` conflicting with manual zoom
* Fix `--zoom <percent> --auto-zoom` logic according to the `man feh` description
* Fix `feh_draw_checks` not taking the zoom level into account properly
* Fix `feh_draw_checks` being called before the zoom level is adjusted
* Prevent `--zoom <percent>` from blocking `--scale-down` in fullscreen / fixed …
=> Fix zoom ratio calculation

src/slideshow.c
=> Prevent the premature abort of the automatic-slideshow if only one image is there

src/winwidget.c
This fixes part 3 of #310:
> when image is rotated at native resolution (100% zoom), anti-aliasing seems to be not applied; this should probably be fixed
=> Antialias rotated images (even at native resolution)

src/gib_imlib.c, src/gib_imlib.h, src/imlib.c
Fixes <https://github.com/derf/feh/issues/397> I think.
Tested on all files from <https://github.com/recurser/exif-orientation-examples>: With this patch they all look identical (when `--auto-rotate` is on), without it only some of them do.
=> Add missing EXIF rotations.

src/imlib.c, src/options.c, src/options.h
This new `--no-inplace-edit` option makes the image manipulations done by <, >, _, | transient.
If you ask me, this should be the default setting.
> [feh does support rotation without changing the file.
...
However it does not snap to 90° angles and there are no keyboard shortcuts for it. Keyboard shortcuts for this type of rotation (in 90° steps) will be added.](https://github.com/derf/feh/issues/86#issuecomment-14922457)
Closes: https://github.com/derf/feh/issues/167
Possibly closes: https://github.com/derf/feh/issues/86
This fixes part 1 of: https://github.com/derf/feh/issues/310
@teleshoes suggested to additionally add a `--rotate=[90;180;270;EXIF]` option.
=> Add an option to disable inplace edit

src/main.c
ft is already checked on line 153 so this condition is useless. Check https://github.com/derf/feh/issues/440 for more details
=> There is no need to test ft against null

src/winwidget.c
Sometimes, X11 won't actually resize a window to the provided size with `X11ResizeWindow`, like if the window manager forces it to stay maximized. This pull request ensures the window's width and height properties are what X11 actually has.
This fixes #446 - KDE (in my case) was sending ConfigureNotify events with the maximized width and height. Feh thought the window's width and height were what it had calculated, instead of what X11 forced, and decided to rerender which caused a flash.
=> Check that window geometry is accurate

src/wallpaper.c
When setting wallpapers without --no-fehbg option, a ~/.fehbg file is
created. This file is set to be an executable for later re-use.
Calling stat() without checking the return value can lead to issues.
If the call fails, then s.st_mode is undefined and excessive permissions
could be set to .fehbg, at worst even setuid/setgid bits for a world
writable file.
While adjusting this, I changed the code to use fstat() and fchmod() to
avoid a further -- but very unlikely -- issue: race condition in form of
TOCTOU. If the file ~/.fehsetbg is replaced by a symlink right before
the chmod call, then a different file would be set executable + the
default mode of the (newly created) file. I don't expect this to be a
real world issue but changed this part "while at it" anyway for more
robust code and a …
=> Check stat for error before setting permissions.

src/events.c
This can happen with images that have ridiculous dimensions.
=> events: guard against NULL returns from imlib calls

man/feh.pre, src/options.c, src/options.h, src/winwidget.c
Fixes https://github.com/derf/feh/issues/180 I guess. Not sure that window ID is even possible, but the class hint is fairly easy. `--class` is what other tools call it too, so I went with it (no short argument though, I doubt that's necessary).
=> Allow setting the X11 class hint as an option.

src/imlib.c
Building feh 3.3 on CentOS 7 x86_64 warns `curl_quit_function` in `imlib.c` is unused:
```
cc -g -O2 -Wall -Wextra -pedantic -std=c11 -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DHAVE_LIBCURL -DHAVE_VERSCMP -DHAVE_LIBXINERAMA -DHAVE_LIBEXIF -DPREFIX=\"/usr/local\" -DPACKAGE=\"feh\" -DVERSION=\"3.3\"   -c -o imlib.o imlib.c
imlib.c:545:12: warning: ‘curl_quit_function’ defined but not used [-Wunused-function]
static int curl_quit_function(void *clientp,  curl_off_t dltotal,  curl_off_t dlnow, curl_off_t ultotal, curl_off_t ulnow)
^
```
The `curl_quit_function` code was added in response to pull [#435](https://github.com/derf/feh/pull/435)
In issue [#485](https://github.com/derf/feh/issues/485) a fellow CentOS 7 user had an error building feh because CentOS 7 is locked into an old …
=> Quit curl cleanly even if libcurl is old.

src/imlib.c, src/options.c, src/options.h
feh attempts to re-fetch each http source in a slideshow when going back and forth between images. This patch adds the flag `--use-http-cache`, enabling which allows feh to use the previously downloaded files.
=> Enable re-using downloaded http cache

README.md, config.mk, man/Makefile, man/feh.pre, src/Makefile, src/feh.h, src/filelist.c, src/options.c, src/strverscmp.c
The --version-sort option requires strverscmp(), but this is a glibc
extension that does not exist on OpenBSD and other systems. To enable
--version-sort on those systems, provide an internal implementation of
strverscmp(). The implementation is from the musl C library and is
MIT-licensed.
The build process remains the same: the verscmp flag should be set to 1
only if strverscmp() is available in libc. If verscmp is 0, then the
internal implementation is used.
Tested on OpenBSD and Debian.
=> Enable --version-sort on systems without strverscmp()

man/feh.pre, src/help.raw, src/keyevents.c, src/slideshow.c
I use feh to display image slideshows that can be toggled via remote. For long delays between images, I was missing a visual cue to tell whether the slideshow was running or paused.
This can now be achieved via the %a format specifier in the `--info` option.
I used 'a' because it was one of the few free letters, but if someone comes up with a more intuitive name, I am happy to change it.
=> add option 'a' to show play/paused information in slideshow mode

man/feh.pre
This helps ensure the man implementation has consistent spacing between sentences.
```
feh.1:588:33: WARNING: new sentence, new line
```
=> man: Silence mandoc warning.

.github/workflows/c.yml, ChangeLog, man/feh.pre, src/feh.h, src/filelist.c, src/help.raw, src/imlib.c, src/index.c, src/menu.c, src/options.c, src/options.h, src/slideshow.c, src/thumbnail.c, src/timers.c, src/timers.h, src/winwidget.c, test/feh.t
Yet another `feh` option… This lets `feh` draw the background pixmap of an existing window, opening the door for use with tools like `xscreensaver` or `xsecurelock`
I opened this in response to #180, which was closed a long while ago but mentioned this functionality. I'm personally using this patch to display my wallpaper with `xsecurelock` for a seamless desktop/lock screen transition
This has always been one of my favorite pieces of software and I'm hoping the extra flag is justified for others to integrate it with their own setups! :tada:
=> Add windowid option to draw to an existing window

src/wallpaper.c
Moved the .fehbg script into its own function to improve readability.
Updated so that the script is now generated with an absolute path to the feh executable that was used during the invocation that generate the .fehbg script.
resolves #587
=> .fehbg script now uses absolute file paths instead of the relative path

src/imlib.c
Small change to make feh recognize the magic number for JPEG XL files (raw codestream or container) to avoid having to set FEH_SKIP_MAGIC when using imlib2-jxl (https://github.com/alistair7/imlib2-jxl).
This mimics the change for heic/heif as closely as possible.
=> Add JPEG XL to supported file formats

src/filelist.c
Calling feh with an empty argument leads to out of boundary access.
This can be seen best when compiled with asan:
$ feh ""
=> Fix out of boundary access on illegal argument

src/imlib.c
The snprintf string argument should not be duplicated.
It is not needed and also not released afterwards.
=> Fix memory leak on error path

src/filelist.c
Gets rid of this warning:
```
filelist.c: In function ‘strcmp_or_strverscmp’:
filelist.c:414:10: warning: implicit declaration of function ‘strverscmp’; did you mean ‘strncmp’? [-Wimplicit-function-declaration]
414 |   return(strverscmp(s1, s2));
|          ^~~~~~~~~~
|          strncmp
```
=> Fix implicit definition of `strverscmp`.

README.md, config.mk, src/feh.h, src/imlib.c, src/main.c
Writing our own magic bytes detection is prone to errors and an
everlasting catch-up-game. Let's use libmagic to get things right,
this is less code and makes things more reliable.
Building without libmagic is still possible. That will make the code
act like specifying FEH_SKIP_MAGIC=1, effectively passing everything
to imlib2.
=> use libmagic to detect valid file formats

src/winwidget.c
inotify_add_watch calls fail when the file is a url, since it does not
correspond to an actual on-disk path. The temporary file path fetched by
curl could be kept and monitored, but since this is unlikely to change
just avoid monitoring files opened via a url.
=> winwidget: do not add an inotify watch if file is a url

src/feh.h, src/filelist.c, src/filelist.h, src/gib_hash.c, src/gib_hash.h, src/keyevents.c, src/menu.c, src/signals.c, src/signals.h, src/thumbnail.c, src/thumbnail.h
These are no longer supported in upcoming clang versions.
warning: a function declaration without a prototype is deprecated in all versions of C [-Wstrict-prototypes]
Reference: https://archives.gentoo.org/gentoo-dev/message/dd9f2d3082b8b6f8dfbccb0639e6e240
=> src: Fix build with clang 16

Makefile
No need to use `grep -F` here, also silences a deprecation warning from latest GNU grep.
=> Use `grep` instead of `fgrep`

src/strverscmp.c
This PR merges [this musl commit](https://git.musl-libc.org/cgit/musl/commit/?id=b50eb8c36c20f967bd0ed70c0b0db38a450886ba). It fixes a sorting problem where, for example, the sequence `09.jpg`, `10.jpg`, `foo.jpg` would be incorrectly sorted as `09.jpg`, `foo.jpg`, `10.jpg`.
=> Sync strverscmp.c with upstream musl

man/feh.pre
There's a place, under BACKGROUND SETTING, where it says to use `xrandr --listmonitor` to determine how Xinerama monitor IDs map to screens etc. This should be `xrandr --listmonitors` with an 's' at the end.
=> Small error in man-page

src/filelist.c, src/filelist.h, src/list.c, src/menu.c, src/slideshow.c
When the user requests sorting by size or mtime, do a "soft preload" of the file list that only calls stat(2) without loading images. This avoids calling stat(2) repeatedly on the same files when sorting the file list, and achieves faster startup on slow filesystems.
Closes https://github.com/derf/feh/issues/694
=> cache stat(2) calls

man/feh.pre, src/events.c, src/help.raw, src/options.c, src/options.h
I have implemented simple tap zones as described in derf/feh#726.
The tap zones can be activated with the newly introduced `--tap-zones` command line switch. They are disabled by default. So there is no change in the default behavior for feh. For now, I have only implemented tap zones for previous/next file actions.
=> Add support for simple tap zones
